config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :update]
  resources :programs do
    resources :meals, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :program
  has_many :menu_items

  def date
    start_time.strftime("%a, %B %d, %Y")
  end

  def time_range
    "#{time(start_time)} - #{time(end_time)}"
  end

  def time(t)
    t.strftime("%l:%M %P")
  end
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :meal
end

app/models/program.rb
class Program < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :meals
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :programs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def create
    meal = Meal.create!(description: description, start_time: start_time, end_time: end_time, program: program)
    redirect_to user_path(current_user)
  end

  private

  def program
    Program.find(params["program_id"])
  end

  def description
    params["meal"]["description"]
  end

  def start_time
    datetime("start_time")
  end

  def end_time
    datetime("end_time")
  end

  def datetime(f)
    Time.zone = "Chicago/America"
    Time.zone.local(year(f), month(f), day(f), hour(f), minute(f))
  end

  %i(year month day hour minute).each_with_index do |method_name, i|
    define_method(method_name) do |field|
      params["meal"]["#{field}(#{i+1}i)"].to_i
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @programs = Program.all.order(:name)
    @user_programs = current_user.programs.order(:name)
  end

  def update
    current_user.programs << program
    current_user.save!
    redirect_to user_path(current_user)
  end

  private

  def program
    Program.find(program_id)
  end

  def program_id
    # TODO: fix this monstrosity
    params["user"]["programs"]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | HackhungerApp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.7/js/tether.min.js'

  body.bg-faded
    .container
      div.notice
        div.alert-success= notice
      div.alert
        div.alert-warning= alert
      = yield

app/views/users/show.slim
-if current_user.programs.any?
  h1
    | My Programs
  -@user_programs.map do |program|
    p=program.name

    h4
      | Planned Meals:
    -program.meals.map do |meal|
      div= meal.date
      div= meal.time_range

      div Menu Items:
      -meal.description.split("\n").map do |d|
        div=d
      br
    br

    h4
      | Add a Meal:
    = form_for(Meal.new, url: program_meals_path(program)) do |f|
      .form-group
        = f.label(:description)
        br
        = f.text_area(:description)
        br
        = f.label(:start_time)
        = f.datetime_select(:start_time, default: 3.days.from_now.beginning_of_day + 11.hours)
        br
        = f.label(:end_time)
        = f.datetime_select(:end_time, default: 3.days.from_now.beginning_of_day + 14.hours)
      .actions
        = f.submit "Add Meal"

    br
    br
h3
  | Add a Meal Program to Manage:

= form_for(current_user, url: user_path) do |f|
  .form-group
    = f.select(:programs, options_for_select(@programs.map { |p| [p.name, p.id]}))
  .actions
    = f.submit "Manage Program"
  br
  br
  br
  br
  br
  br

app/views/welcome/index.slim
-if current_user
  p=current_user.email
  div=link_to "Log Out", "/users/sign_out", method: "delete"
  div=link_to "My Profile", "/users/#{current_user.id}"
-else
  div=link_to "Sign In", "/users/sign_in"